### ISSUE TITLE
Photo Grid no longer working 

### ISSUE THREAD

**Issue by JPhilpin** [cleverdevil/microgram#7]
- has been fine - no changes made - i checked on microblog and Simon EWoods noticed the issue also - i wonder if some of the recent manton changes has affected things ?

**Comment by arjwright** [comment]
Noticing this issue now as well. Today has been the 1st day since the major update that I’ve posted an image, so there was nothing to alert me that there was something potentially happening. 

At the moment, I’m getting my custom CSS showing the blocks, but the thumbnails themselves are not showing. I’ve attached a screenshot to show what my site (http://avancee.agency/scribbles) looks like at the time of this posting.

BTW: Other than customized CSS, there’s nothing changed about my implementation of this feature.

![53785713-b41b-4690-b58d-0345db1b4c89](https://user-images.githubusercontent.com/1577432/52490878-c7930a00-2b93-11e9-9aac-50cd48853ca1.png)

**Comment by cleverdevil** [comment]
Thanks for the report, folks. I think there's something up in Micro.blog itself. I've pinged @manton over there as well!
